# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20161128_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
