# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20161129_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_beyer',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
