# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20161129_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pruct_active',
            new_name='product_active',
        ),
    ]
