# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20161130_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(default='exit', upload_to=b''),
            preserve_default=False,
        ),
    ]
