# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='static/products'),
        ),
    ]
