# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20161130_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='media'),
        ),
    ]
