# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20161130_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_seller', models.CharField(max_length=128)),
                ('transaction_beyer', models.CharField(max_length=128)),
                ('transaction_product', models.CharField(max_length=128)),
                ('transaction_amount', models.PositiveIntegerField()),
                ('transaction_date', models.DateField(null=True)),
                ('transaction_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to=b''),
        ),
    ]
